import { Question } from "./ApiManager";

const _pmd_001: Question[] = [
  { gameId: "_pmd_001", questionStr: "Hvem er morsomst?" },
  { gameId: "_pmd_001", questionStr: "Hvem tror selv den er morsomst?" },
  { gameId: "_pmd_001", questionStr: "Hvem har størst kjendisfaktor?" },
  { gameId: "_pmd_001", questionStr: "Hvem har søtest familie?" },
  { gameId: "_pmd_001", questionStr: "Hvem har hatt sex med flest yngre?" },
  {
    gameId: "_pmd_001",
    questionStr: "Hvem kunne hatt sex med flest i klassen?",
  },
  { gameId: "_pmd_001", questionStr: "Hvem er mest opptatt av utsjånaden?" },
  {
    gameId: "_pmd_001",
    questionStr: "Hvem er mest fornøyd med eiga utsjånad?",
  },
  { gameId: "_pmd_001", questionStr: "Hvem komme raskast?" },
  { gameId: "_pmd_001", questionStr: "Hvem har minst penis?" },
  { gameId: "_pmd_001", questionStr: "Hvem er størst i kjeften?" },
  { gameId: "_pmd_001", questionStr: "Hvem er mest overlegen?" },
  { gameId: "_pmd_001", questionStr: "Hvem er mest sporty?" },
  { gameId: "_pmd_001", questionStr: "Hvem har hatt sex med flest?" },
  { gameId: "_pmd_001", questionStr: "Hvem har hatt flest orgasmar?" },
  { gameId: "_pmd_001", questionStr: "Hvem er mest vill?" },
  { gameId: "_pmd_001", questionStr: "Hvem har best kropp?" },
  { gameId: "_pmd_001", questionStr: "Hvem er mest spontan?" },
  { gameId: "_pmd_001", questionStr: "Hvem er mest uskyldige?" },
  { gameId: "_pmd_001", questionStr: "Hvem laga dei sjukaste lydene i senga?" },
  { gameId: "_pmd_001", questionStr: "Hvem ler mest i timen?" },
  { gameId: "_pmd_001", questionStr: "Hvem har finast antrekk?" },
  { gameId: "_pmd_001", questionStr: "Hvem smisker mest med læreren?" },
  { gameId: "_pmd_001", questionStr: "Hvem har mest spennende rumpe?" },
  { gameId: "_pmd_001", questionStr: "Hvem kunne prostituert seg?" },
  { gameId: "_pmd_001", questionStr: "Hvem stirrer mest i timene?" },
  { gameId: "_pmd_001", questionStr: "Hvem er den mest voldelige jenta?" },
  { gameId: "_pmd_001", questionStr: "Hvem spiser mest?" },
  { gameId: "_pmd_001", questionStr: "Hvem har diggest pupper?" },
  { gameId: "_pmd_001", questionStr: "Hvem vil du danse med i kveld?" },
  { gameId: "_pmd_001", questionStr: "Hvilken jente er mest bro?" },
  {
    gameId: "_pmd_001",
    questionStr: "Hvilken gutt får du vakrast barn saman med?",
  },
  { gameId: "_pmd_001", questionStr: "Hvem har du et lite mye til?" },
  { gameId: "_pmd_001", questionStr: "Hvem har shava og er forberedt på alt?" },
  {
    gameId: "_pmd_001",
    questionStr: "Hvem hadde vært den beste telefonselgeren?",
  },
  { gameId: "_pmd_001", questionStr: "Hvem er den største fylliken?" },
  { gameId: "_pmd_001", questionStr: "Hvilken gutt får du vakrest barn med?" },
  { gameId: "_pmd_001", questionStr: "Hvem er den beste til å kysse?" },
  { gameId: "_pmd_001", questionStr: "Hvem ler mest i timen?" },
  { gameId: "_pmd_001", questionStr: "Har lyst å komme i buksa på i kveld?" },
  { gameId: "_pmd_001", questionStr: "Hvem blir raskast sjalu?" },
  { gameId: "_pmd_001", questionStr: "Hvem ligner mest på en taco?" },
  { gameId: "_pmd_001", questionStr: "Hvem har hatt sex med flest eldre?" },
  { gameId: "_pmd_001", questionStr: "Hvem har hatt trekant?" },
  { gameId: "_pmd_001", questionStr: "Hvem har hatt sex med flest årskull?" },
  { gameId: "_pmd_001", questionStr: "Hvem er mest flørtete?" },
  { gameId: "_pmd_001", questionStr: "Hvem er hyggeligst?" },
  { gameId: "_pmd_001", questionStr: "Hvem snakker mest engelsk?" },
  {
    gameId: "_pmd_001",
    questionStr: "Hvem er mest desperat etter å miste jomfrudommen?",
  },
  { gameId: "_pmd_001", questionStr: "Hvem er den vakreste i rommet?" },
  { gameId: "_pmd_001", questionStr: "Hvem stoler du mest på?" },
  { gameId: "_pmd_001", questionStr: "Hvem tar med seg nåken heim i kveld?" },
  { gameId: "_pmd_001", questionStr: "Hvem får kjæreste i år?" },
  { gameId: "_pmd_001", questionStr: "Hvem blir gravid først?" },
  { gameId: "_pmd_001", questionStr: "Hvem spyr i kveld?" },
  { gameId: "_pmd_001", questionStr: "Hvem slutta på studiet?" },
  { gameId: "_pmd_001", questionStr: "Hvem blir mest drita i kveld?" },
  { gameId: "_pmd_001", questionStr: "Hvem blir pappa først?" },
  { gameId: "_pmd_001", questionStr: "Hvem gifta seg først?" },
  { gameId: "_pmd_001", questionStr: "Hvem har finast lepper?" },
  { gameId: "_pmd_001", questionStr: "Hvem burde vært elevråd?" },
  { gameId: "_pmd_001", questionStr: "Hvem burde ikke vært elevråd?" },
  { gameId: "_pmd_001", questionStr: "Hvem er minst?" },
  { gameId: "_pmd_001", questionStr: "Hvem er mest langsint?" },
  { gameId: "_pmd_001", questionStr: "Hvem mest sannsynlig til å prøve anal?" },
  { gameId: "_pmd_001", questionStr: "Hvem mest sannsynlig lebisk/homofil?" },
  {
    gameId: "_pmd_001",
    questionStr: "Hvem kunne hatt sex me samme kjønn, uten å være homofil?",
  },
  { gameId: "_pmd_001", questionStr: "Hvem er tøffest?" },
  { gameId: "_pmd_001", questionStr: "Hvem lyser opp rommet?" },
  { gameId: "_pmd_001", questionStr: "Hvem har runka mest?" },
  { gameId: "_pmd_001", questionStr: "Hvem tar seg mest på brysta?" },
  { gameId: "_pmd_001", questionStr: "Hvem ser mest på porno?" },
  { gameId: "_pmd_001", questionStr: "Hvem finger mest?" },
  { gameId: "_pmd_001", questionStr: "Hvem drikker raskast?" },
  { gameId: "_pmd_001", questionStr: "Hvem gifter seg for penger?" },
  { gameId: "_pmd_001", questionStr: "Hvem tar plastisk operasjon?" },
  { gameId: "_pmd_001", questionStr: "Hvem tar farligst forbikjøringer?" },
  {
    gameId: "_pmd_001",
    questionStr: "Hvem hat gjort mest for å vinne et veddemål?",
  },
  { gameId: "_pmd_001", questionStr: "Hvem ender opp som kriminell?" },
  { gameId: "_pmd_001", questionStr: "Hvem har blitt pumpa?" },
  { gameId: "_pmd_001", questionStr: "Hvem er den beste sjåføren?" },
  { gameId: "_pmd_001", questionStr: "Hvem handler mest på salg?" },
  { gameId: "_pmd_001", questionStr: "Hvem er jomfru lengst?" },
  { gameId: "_pmd_001", questionStr: "Hvem ville du vært på en øde øy med?" },
  { gameId: "_pmd_001", questionStr: "Hvem er det største talentet?" },
];

const _pmd_002: Question[] = [
  {
    gameId: "_pmd_002",
    questionStr: "Hvem er minst flink til å bruke prevensjon?",
  },
  { gameId: "_pmd_002", questionStr: "Hvem slutter på studiet" },
  { gameId: "_pmd_002", questionStr: "Hvem har mest kinky sex?" },
  { gameId: "_pmd_002", questionStr: "Hvem har en kjønnssykdom akkurat nå?" },
  { gameId: "_pmd_002", questionStr: "Hvem har hatt flest orgasmer?" },
  { gameId: "_pmd_002", questionStr: "Hvem sprer mest rykter?" },
  { gameId: "_pmd_002", questionStr: "Hvem er dagens 0?" },
  { gameId: "_pmd_002", questionStr: "Hvem er gravid akkurat nå?" },
  {
    gameId: "_pmd_002",
    questionStr: "Hvem har shavet og er forberedt på alt?",
  },
  { gameId: "_pmd_002", questionStr: "Hvem har klippekort på abortklinikken?" },
  {
    gameId: "_pmd_002",
    questionStr: "Hvem er mest sannsynlig til å ha trekant med tvillinger?",
  },
  { gameId: "_pmd_002", questionStr: "Hvem er mest ubesluttsom?" },
  { gameId: "_pmd_002", questionStr: "Hvem er en golddigger?" },
  {
    gameId: "_pmd_002",
    questionStr: "Hvem har du lyst å komme i buksa på i kveld?",
  },
  { gameId: "_pmd_002", questionStr: "Hvem er mest kåt?" },
  { gameId: "_pmd_002", questionStr: "Hvem får du vakrest barn med?" },
  { gameId: "_pmd_002", questionStr: "Hvem er mest hang imorgen?" },
  { gameId: "_pmd_002", questionStr: "Hvem har blitt pumpa?" },
  {
    gameId: "_pmd_002",
    questionStr: "Hvem bruker mest tid på å shave pikken/fitta?",
  },
  { gameId: "_pmd_002", questionStr: "Hvem er mest fuckboy?" },
  { gameId: "_pmd_002", questionStr: "Hvem lager de sykeste lydene i senga?" },
  { gameId: "_pmd_002", questionStr: "Hvem er mest luremus?" },
  { gameId: "_pmd_002", questionStr: "Hvem har de sykeste fetishene?" },
  {
    gameId: "_pmd_002",
    questionStr: "Hvem er mest fornøyd med eget utseende?",
  },
  { gameId: "_pmd_002", questionStr: "Hvem ser mest på porno?" },
  { gameId: "_pmd_002", questionStr: "Hvem fingrer mest?" },
  { gameId: "_pmd_002", questionStr: "Hvem spyr ikveld?" },
  {
    gameId: "_pmd_002",
    questionStr: "Hvem havner på rommet til hosten med noen ikveld?",
  },
  { gameId: "_pmd_002", questionStr: "Hvem er mest sjalu?" },
  { gameId: "_pmd_002", questionStr: "Hvem tar mest drugs?" },
  { gameId: "_pmd_002", questionStr: "Hvem har spenstige tits?" },
  { gameId: "_pmd_002", questionStr: "Hvem snakker minst?" },
  { gameId: "_pmd_002", questionStr: "Hvem gir mest til veldedighet?" },
  {
    gameId: "_pmd_002",
    questionStr: "Hvem spurter den mest massive cumshoten?",
  },
  {
    gameId: "_pmd_002",
    questionStr: "Hvem får klamma i øyet av den mest massive cumshoten?",
  },
  { gameId: "_pmd_002", questionStr: "Hvem dauver av kreft?" },
  { gameId: "_pmd_002", questionStr: "Hvem hadde sex sist?" },
  { gameId: "_pmd_002", questionStr: "Hvem runker mest?" },
  { gameId: "_pmd_002", questionStr: "Hvem har thiccest ass?" },
  { gameId: "_pmd_002", questionStr: "Hvem kommer raskest?" },
  { gameId: "_pmd_002", questionStr: "Hvem kom i puberteten sist?" },
  { gameId: "_pmd_002", questionStr: "Hvem har størst pikk?" },
  { gameId: "_pmd_002", questionStr: "Hvem driver mest blasfemi?" },
  { gameId: "_pmd_002", questionStr: "Hvem blir forelder først?" },
  { gameId: "_pmd_002", questionStr: "Hvem vinner Farmen?" },
  { gameId: "_pmd_002", questionStr: "Hvem kramper neste år?" },
  { gameId: "_pmd_002", questionStr: "Hvem har du et godt øye til?" },
  { gameId: "_pmd_002", questionStr: "Hvem har hatt det vanskeligste livet?" },
  { gameId: "_pmd_002", questionStr: "Hvem er mest lilla?" },
  { gameId: "_pmd_002", questionStr: "Hvem er mest desp?" },
  { gameId: "_pmd_002", questionStr: "Hvem griner mest?" },
  {
    gameId: "_pmd_002",
    questionStr: "Hvem blir sendt ut av Ex on The Beach av Padden?",
  },
  {
    gameId: "_pmd_002",
    questionStr: "Hvem er dårligst på å holde hemmeligheter?",
  },
  { gameId: "_pmd_002", questionStr: "Hvem er hyggeligere enn de ser ut som?" },
  { gameId: "_pmd_002", questionStr: "Hvem er den største nevemagneten?" },
  { gameId: "_pmd_002", questionStr: "Hvem er største snaphora?" },
  { gameId: "_pmd_002", questionStr: "Hvem klår mest?" },
  { gameId: "_pmd_002", questionStr: "Hvem bryr seg minst om hvem de hooker?" },
  { gameId: "_pmd_002", questionStr: "Hvem mista jomfrudommen først?" },
  { gameId: "_pmd_002", questionStr: "Hvem vil du se naken?" },
  { gameId: "_pmd_002", questionStr: "Hvem tar seg mest på puppene sine?" },
  { gameId: "_pmd_002", questionStr: "Hvem har flest psykiske lidelser?" },
  { gameId: "_pmd_002", questionStr: "Hvem skaper mest drama i hotellet?" },
  { gameId: "_pmd_002", questionStr: "Hvem savner RT mest?" },
  { gameId: "_pmd_002", questionStr: "Hvem investerer mest aksjer?" },
  { gameId: "_pmd_002", questionStr: "Hvem dauver av overdose?" },
  { gameId: "_pmd_002", questionStr: "Hvem har dårligst humor?" },
  { gameId: "_pmd_002", questionStr: "Hvem ødelegger mest?" },
  {
    gameId: "_pmd_002",
    questionStr: "Hvem er mest sannsynlig til å spille inn porno film?",
  },
  { gameId: "_pmd_002", questionStr: "Hvem hadde banga broren/søsteren sin?" },
  { gameId: "_pmd_002", questionStr: "Hvem er mest dramaqueen?" },
  { gameId: "_pmd_002", questionStr: "Hvem har mange soveplasser?" },
  {
    gameId: "_pmd_002",
    questionStr: "Hvem gifter seg med en som har gått på BI?",
  },
];

export { _pmd_001, _pmd_002 };
